### ISSUE TITLE
SVD did not converge in Linear Least Squares

### ISSUE THREAD

**Issue by Hoankaka15** [ShuhuaGao/geppy#16]
Hi Shuhua,

I have modified the example: 'numerical_expression_inference-Linear_scaling.ipynb' by modifying the input function: f(x)=x**1.5. Then adding pset.add_function(operator.pow, 2). However, a problem occurred as numpy.linalg.LinAlgError: SVD did not converge in Linear Least Squares.

Please give me some advice on how to overcome this issue.

Thanks,
Hoan Nguyen

**Comment by ShuhuaGao** [comment]
Please check whether the matrix `Q` in `np.linalg.lstsq(Q, Y, rcond=None) ` is singular.

Besides, you may want to refer to the documentation of `np.linalg.lstsq`. I don't have clues about this error either.

**Comment by Hoankaka15** [comment]
> Please check whether the matrix `Q` in `np.linalg.lstsq(Q, Y, rcond=None) ` is singular.
> 
> Besides, you may want to refer to the documentation of `np.linalg.lstsq`. I don't have clues about this error either.

Thanks for your reply. If finding anything, I will note here.

**Comment by TristanHehnen** [comment]
I had a similar issue, on a different case however. While trying to smooth some measurement data with `savgol` from `scipy` I encountered the "SVD did not converge in Linear Least Squares" error. 

It turned out, that the measurement data was messed up at the beginning and the end, where the x-values were occasionally backtracking, see attached image for example. After cleaning the data by cutting the beginning and end, everything went fine.

Maybe this could be related to your issue.


![Screenshot_14](https://user-images.githubusercontent.com/34650649/77828369-4beb7800-711b-11ea-9447-3495beab05d3.png)
