### ISSUE TITLE
Deep learning, aka tensor based input and functions

### ISSUE THREAD

**Issue by cxbxmxcx** [ShuhuaGao/geppy#18]
Hey there,

Really great work, been looking for a library like this in Python for a while.

Have you thought or considered integrating your package to use tensor input and operations etc.? 

So instead of resolving to a function you may resolve to some deep learning network configuration.  I am wondering if this is something you have considered.  My interest would be to upgrade your package to support tensor operations etc.

Anyway, fantastic work.

Cheers,

Micheal

**Comment by ShuhuaGao** [comment]
Hi, Micheal,

Thanks for your interest and advice. It would be great if you could upgrade it to support tensors.

By the way,  do you want the backpropagation stuff as well? If so, it seems you are doing neuroevolution (or more generally, neural architecture search (NAS)). If this is what you, there should be better alternatives. You may like to read some papers since NAS is a hot topic.

Anyway, it would be helpful even if only tensors like these from PyTorch are supported. We may depend on it to leverage GPU acceleration.  Currently, I am not familiar enough with this field. You may fork this project and play with it. Have fun!

**Comment by minkymorgan** [comment]
Hi Micheal - I love the idea, and if you try, I would be interested in helping where I can.
