### ISSUE TITLE
How to set n_genes = 3

### ISSUE THREAD

**Issue by Tacitate** [ShuhuaGao/geppy#19]
Hello!

I want to set n_genes = 3, but since I did it, it throwed a error as the following:

![image](https://user-images.githubusercontent.com/44204884/71482137-05e0f880-283c-11ea-87fe-3a8b7f2d165d.png)

![image](https://user-images.githubusercontent.com/44204884/71482125-f19cfb80-283b-11ea-8139-06a767fc21ae.png)

**Comment by ShuhuaGao** [comment]
Note the last but one line of your error information: there is a `linker` function. I guess you are using an `add` as the linker, which by default only accepts two arguments like `a + b`. In GEP, the output of each gene acts as an argument of the linker function. There are three arguments in your case, and an error thus happens.

You should provide a custom addition function as the linker that accepts three addends instead of two.

**Comment by Tacitate** [comment]
Soga~ got it,  thx~
