### ISSUE TITLE
how to generate all the expressions on a given primitive set?

### ISSUE THREAD

**Issue by nickhuangxinyu** [ShuhuaGao/geppy#32]
I think when i confirmed the primitive set. the expression tree space is confirmed( the number of expression trees for a fixed depth).

How can i generate them all?

I think genFull or genHalf is randomly generator, how can i generate all without missing?

Thanks

**Comment by ShuhuaGao** [comment]
It is a combinatorial problem. The number of all expressions can be huge. If you like it, just fill the *gene* with each possible primitive. You can check [generate_genome](https://github.com/ShuhuaGao/geppy/blob/e9a6459e13694baf738ebf4b555ab3cf48d03960/geppy/tools/generator.py#L12) for details. This function is used in `Gene` [construction](https://github.com/ShuhuaGao/geppy/blob/e9a6459e13694baf738ebf4b555ab3cf48d03960/geppy/core/entity.py#L138).

**Comment by nickhuangxinyu** [comment]
thanks shuhua.

yes, it's very huge. check all possible expression maybe too time costly.

one more question, which kind of crossover wont change the expression's depth?

cxOnePoint is not a good one, since it will change the expressions' depth

**Comment by nickhuangxinyu** [comment]
For example, two exprs, which depth is 4, and 5
the offspring's depth can be 6.
As csOnePoint swap the subtree of two exprs, so the offspring's depth can be growed

**Comment by ShuhuaGao** [comment]
All crossover methods are stochastic in nature, and none of them is designed to preserve the tree depth. In fact, since the two parents are randomly chosen, I am afraid it is not possible to design a crossover operator that does not change depth. 

A workaround is to perform some post-modification. For instance, if the child is of depth 6 and you want 5, you may try to replace some function primitive with a terminal primitive. Again, I guess it is very cumbersome and not appropriate in GEP.

**Comment by ShuhuaGao** [comment]
You may try the classic tree-based GP if you really want to control tree depth. The DEAP framework has some basic support of [GP](https://deap.readthedocs.io/en/master/tutorials/advanced/gp.html).

**Comment by nickhuangxinyu** [comment]
thx a lot!
