### ISSUE TITLE
gep_simplify can't be used in evaluation

### ISSUE THREAD

**Issue by bolz213** [ShuhuaGao/geppy#5]
When I tried the example "numerical_expression_inference-RNC", I attempted to modify the evaluation function. I called gep_simplify in the evaluation function:

```
def evaluate(individual):
    """Evalute the fitness of an individual: MAE (mean absolute error)"""
    func = toolbox.compile(individual)
    Yp = np.array(list(map(func, X)))
    individual_simplified = gep.simplify(individual)
    x_occrrence = str(individual_simplified).count("x")
    
    return np.mean(np.abs(Y - Yp)), x_occrrence
```

However when I started the evolution I always got error:

```
 ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-de916872db16> in <module>
      8 # start evolution
      9 pop, log = gep.gep_simple(pop, toolbox, n_generations=n_gen, n_elites=1,
---> 10                           stats=stats, hall_of_fame=hof, verbose=True)

~/Projects/geppy/geppy/algorithms/basic.py in gep_simple(population, toolbox, n_generations, n_elites, stats, hall_of_fame, verbose)
     98         invalid_individuals = [ind for ind in population if not ind.fitness.valid]
     99         fitnesses = toolbox.map(toolbox.evaluate, invalid_individuals)
--> 100         for ind, fit in zip(invalid_individuals, fitnesses):
    101             ind.fitness.values = fit
    102 

<ipython-input-9-7da034cb5577> in evaluate(individual)
      3     func = toolbox.compile(individual)
      4     Yp = np.array(list(map(func, X)))
----> 5     individual_simplified = gep.simplify(individual)
      6     x_occrrence = str(individual_simplified).count("x")
      7 

~/Projects/geppy/geppy/support/simplification.py in simplify(genome, symbolic_function_map)
    129             except:
    130                 linker = genome.linker
--> 131             return sp.simplify(linker(*simplified_exprs))
    132     else:
    133         raise TypeError('Only an argument of type KExpression, Gene, and Chromosome is acceptable. The provided '

TypeError: unsupported operand type(s) for +: 'Add' and 'str'
```

I tested the gep_simplify called at the post-processing part and it worked well there. I tried but could not find the problem. Thank you very much if you can help.

**Comment by ShuhuaGao** [comment]
Hi, there was indeed a bug in simplification. I have fixed it. 

However, I am afraid there are still other errors you may encounter if you use `gep.simplify` in the intermediate evolution stage, for example, `ZeroDivisionError`. Note that we have provided a protected version of division to be used in model evaluation. However, in the above example's simplification process, the `protected_div` is replaced by a normal division during symbolic simplification. Thus, it is quite possible that some numeric errors may happen. 

However, if you only use `gep.simplify` in postprocessing for several *top* individuals, it is rare that a `ZeroDivisionError` can be caused, because generally a model with such kind of numeric error will NOT be chosen by the evolution as the best one.

I guess you want to adopt multi-objective evolution and the 2nd objective is the model *complexity*.  In literature, a common complexity measure for tree structured GP is the height of the tree encoding the individual. For our GEP case, you may take the length of the K-expression as a measure of model complexity. Another drawback of `gep.simplify` is  its inefficiency which may take much longer time for evolution.

**Comment by bolz213** [comment]
Thank you very much 👍 . Could you give some clues why this bug only occurs in the evaluation process and in the post-processing it works well?

**Comment by ShuhuaGao** [comment]
I changed this [line](https://github.com/ShuhuaGao/geppy/blob/030504eb64d2e63555b2fdab1699b9ab0f5bc343/geppy/core/symbol.py#L205) to `super().__init__(name, value=None)`. Originally, I mistakenly set `value='symbol'`, and that's why you may encounter adding a string in simplification. 

The above `None` is used in `_simplify_kexpression` [here](https://github.com/ShuhuaGao/geppy/blob/030504eb64d2e63555b2fdab1699b9ab0f5bc343/geppy/support/simplification.py#L48), when the K-expression has only [one element](https://github.com/ShuhuaGao/geppy/blob/030504eb64d2e63555b2fdab1699b9ab0f5bc343/geppy/support/simplification.py#L57), for example, only a variable `x`: `if t.value is None:  # an input`

Originally, we have `t.value` equal to `'symbol'`. Consequently, this condition fails, and `t.value` is returned, which causes the error.

**Comment by ShuhuaGao** [comment]
Why didn't the error happen in postprocessing? I believe it is just a coincidence. As stated above, this error will happen if a gene's K-expression comprises only a single input variable, that is, `x` in the example. The best individuals may not have such a K-expression in the specific example.

Anyway, thank you for pointing out this error!

**Comment by bolz213** [comment]
Thanks!
